server:
  port: 10080

spring:
  application:
    name: cloud-order-service

eureka:
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka

ribbon:
  #建立连接所需时间
  ReadTimeut: 5000
  #建立连接后读取资源的时间
  ConnectTimeout: 5000

logging:
  level:
    #feign日志以什么级别监控哪些接口
    com.qw.springcloud.serivce.PaymentFeignService: debug
